services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
      - /ghost/mysql:/var/lib/mysql

  nginx:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /ghost/nginx/certs:/etc/nginx/certs
      - /ghost/nginx/html:/usr/share/nginx/html
  acme:
    image: nginxproxy/acme-companion:latest
    container_name: acme
    restart: always
    depends_on:
      - nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /ghost/nginx/certs:/etc/nginx/certs
      - /ghost/nginx/html:/usr/share/nginx/html
      - /ghost/acme:/etc/acme.sh

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    depends_on:
      - mysql
      - acme
    env_file:
      - .env
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: https://${URL}
      VIRTUAL_PORT: 2368
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    volumes:
      - /ghost/web:/var/lib/ghost/content
