version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ROOT_PASSWORD: ghost
    volumes:
      - /ghost/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: https://${DOMAIN_NAME}
    volumes:
      - /ghost/web:/var/lib/ghost/content

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    depends_on:
      - ghost
    volumes:
      - /ghost/nginx/config:/config
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${DOMAIN_NAME}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=http
      - EMAIL=${ADMIN_EMAIL}
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped